/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/gym-home`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/registration-type`; params?: Router.UnknownInputParams; } | { pathname: `/user-home`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/ai/generate`; params?: Router.UnknownInputParams; } | { pathname: `/ai`; params?: Router.UnknownInputParams; } | { pathname: `/ai/result`; params?: Router.UnknownInputParams; } | { pathname: `/coaching`; params?: Router.UnknownInputParams; } | { pathname: `/progress`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/add`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/edit`; params?: Router.UnknownInputParams; } | { pathname: `/workouts`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/session`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/view`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/gym-home`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/registration-type`; params?: Router.UnknownOutputParams; } | { pathname: `/user-home`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/ai/generate`; params?: Router.UnknownOutputParams; } | { pathname: `/ai`; params?: Router.UnknownOutputParams; } | { pathname: `/ai/result`; params?: Router.UnknownOutputParams; } | { pathname: `/coaching`; params?: Router.UnknownOutputParams; } | { pathname: `/progress`; params?: Router.UnknownOutputParams; } | { pathname: `/workouts/add`; params?: Router.UnknownOutputParams; } | { pathname: `/workouts/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/workouts`; params?: Router.UnknownOutputParams; } | { pathname: `/workouts/session`; params?: Router.UnknownOutputParams; } | { pathname: `/workouts/view`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/gym-home${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/registration-type${`?${string}` | `#${string}` | ''}` | `/user-home${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/ai/generate${`?${string}` | `#${string}` | ''}` | `/ai${`?${string}` | `#${string}` | ''}` | `/ai/result${`?${string}` | `#${string}` | ''}` | `/coaching${`?${string}` | `#${string}` | ''}` | `/progress${`?${string}` | `#${string}` | ''}` | `/workouts/add${`?${string}` | `#${string}` | ''}` | `/workouts/edit${`?${string}` | `#${string}` | ''}` | `/workouts${`?${string}` | `#${string}` | ''}` | `/workouts/session${`?${string}` | `#${string}` | ''}` | `/workouts/view${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/gym-home`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/registration-type`; params?: Router.UnknownInputParams; } | { pathname: `/user-home`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/ai/generate`; params?: Router.UnknownInputParams; } | { pathname: `/ai`; params?: Router.UnknownInputParams; } | { pathname: `/ai/result`; params?: Router.UnknownInputParams; } | { pathname: `/coaching`; params?: Router.UnknownInputParams; } | { pathname: `/progress`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/add`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/edit`; params?: Router.UnknownInputParams; } | { pathname: `/workouts`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/session`; params?: Router.UnknownInputParams; } | { pathname: `/workouts/view`; params?: Router.UnknownInputParams; };
    }
  }
}
